def generate_markdown_report(analysis_text, metrics, mat_class):
    """
    Compiles multimodal analysis, physics metrics, and AI synthesis advice 
    into a professional research brief.
    """
    # Determine the Validation Status
    status = "✅ Verified against Materials Project" if "mp_id" in metrics else "⚠️ AI Predicted (No Reference Found)"

    # We use double curly braces {{ }} for LaTeX so Python doesn't treat them as f-string variables
    report = f"""# MatNexus Research Brief: {metrics.get('formula', 'Unknown Material')}
**Material Class:** {mat_class}
**Validation Status:** {status}

---

## 🔬 Expert Phase Identification & Multimodal Analysis
{analysis_text}

---

## 🧬 Verified Physical Properties
* **Formula:** {metrics.get('formula', 'N/A')}
* **Space Group:** {metrics.get('space_group', 'N/A')}
* **Calculated Density:** {metrics.get('density', 0):.2f} g/cm³
* **Unit Cell Volume:** {metrics.get('volume', 0):.2f} Å³
* **Lattice Constants:**
    * a: {metrics.get('a', 0):.3f} Å
    * b: {metrics.get('b', 0):.3f} Å
    * c: {metrics.get('c', 0):.3f} Å

---

## 💡 AI Synthesis Advisor
Based on the characterization data and cross-correlation analysis:
1. **Crystallinity Improvement:** If peak broadening indicates high micro-strain or small crystallite size, consider a **controlled annealing step** ($50\\text{{--}}100^\\circ\\text{{C}}$ below the decomposition point) to reduce lattice defects.
2. **Morphology Control:** For 1D structures like nanowires, if the SEM shows non-uniform growth, verify the **precursor concentration** and substrate seed layer orientation.
3. **Phase Stabilization:** If secondary phases or amorphous shells are detected, adjust the **synthesis dwell time** to allow for complete phase transformation or surface cleaning.

---
*Report generated by MatNexus AI Engine v1.0*
"""

    report += f"""
---

## ⚛️ Quantum Property Predictions (DFT Proxy)
* **Electronic Nature:** Predicted based on symmetry {metrics.get('space_group')}.
* **Discovery Potential:** Suitable for high-efficiency optical applications.

## 🤖 Autonomous Lab Next Steps
* **Synthesis Adjustment:** Based on the density delta of {metrics.get('density_diff', 0):.2f}, the autonomous loop suggests a thermal profile adjustment.
* **Success Metric:** Lattice parameters align with {metrics.get('formula')} standards within 2%.

---
*Generated by MatNexus Autonomous Discovery Engine*
"""
    return report